{
    "name": "App One",
    "author": "Mahmoud Hawas",
    "category": "Real Estate",
    "version": "17.0.0.1.0",
    "depends": [
        "base",
        "web",
        "sale_management",
        "account",
        "mail",
        "contacts"
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/data.xml",
        "views/base_menu.xml",
        "views/property_view.xml",
        "views/owner_view.xml",
        "views/tag_view.xml",
        "views/sale_order_view.xml",
        "views/res_partner_view.xml",
        "views/history_view.xml",
        "views/building_view.xml",
        "wizard/change_state_wizard.xml",
        "reports/property_report.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "app_one/static/src/css/property.css",
            "app_one/static/src/components/listView/listView.js",
            "app_one/static/src/components/listView/listView.xml",
            "app_one/static/src/components/listView/listView.css",
            "app_one/static/src/components/formView/formVeiw.js",
            "app_one/static/src/components/formView/formView.xml",
            "app_one/static/src/components/formView/formVeiw.css",
        ],
    },
    "application": True,
}
